CREATE SCHEMA projeto8 AUTHORIZATION jhenifer;


-- Criação da tabela
CREATE TABLE projeto8.tratamentos_medicos (
    id SERIAL PRIMARY KEY,
    paciente_nome TEXT,
    genero TEXT,
    idade INT,
    condicao TEXT,
    tratamento TEXT,
    medico TEXT,
    hospital TEXT,
    plano_saude TEXT
);

-- Inserção dos dados fictícios gerado com Python

INSERT INTO projeto8.tratamentos_medicos(paciente_nome, genero, idade, condicao, tratamento, medico, hospital, plano_saude)
VALUES
('Ana Souza', 'Masculino', 84, 'Depressão', 'Inalador', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Paulo César', 'Masculino', 81, 'Covid-19', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'Amil'),
('Lucas Rocha', 'Outro', 89, 'Depressão', 'Insulina', 'Dra. Costa', 'Hospital Central', 'Bradesco Saúde'),
('Ana Souza', 'Masculino', 75, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Hospital Vida', 'SulAmérica'),
('Gustavo Dias', 'Outro', 72, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Santa Casa', 'Bradesco Saúde'),
('Paulo César', 'Masculino', 29, 'Diabetes', 'Antiviral', 'Dr. Souza', 'Hospital Vida', 'Particular'),
('Juliana Costa', 'Outro', 31, 'Obesidade', 'Insulina', 'Dra. Costa', 'Santa Casa', 'SulAmérica'),
('Carlos Lima', 'Feminino', 18, 'Hipertensão', 'Inalador', 'Dr. Souza', 'Hospital Vida', 'Bradesco Saúde'),
('Beatriz Mendes', 'Masculino', 78, 'Asma', 'Insulina', 'Dra. Costa', 'Hospital Vida', 'Unimed'),
('Beatriz Mendes', 'Masculino', 49, 'Hipertensão', 'Dieta', 'Dr. Souza', 'Santa Casa', 'Amil'),
('Gustavo Dias', 'Outro', 75, 'Obesidade', 'Inalador', 'Dr. Souza', 'Santa Casa', 'Bradesco Saúde'),
('Gustavo Dias', 'Outro', 72, 'Covid-19', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Unimed'),
('João Pedro', 'Feminino', 32, 'Diabetes', 'Inalador', 'Dra. Oliveira', 'Hospital Central', 'Unimed'),
('Ana Souza', 'Masculino', 74, 'Diabetes', 'Inalador', 'Dra. Costa', 'Hospital Vida', 'Amil'),
('João Pedro', 'Masculino', 87, 'Diabetes', 'Antiviral', 'Dr. Souza', 'Hospital Vida', 'Particular'),
('Gustavo Dias', 'Feminino', 54, 'Depressão', 'Psicoterapia', 'Dr. Silva', 'Hospital Central', 'Particular'),
('Juliana Costa', 'Feminino', 27, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Hospital Central', 'SulAmérica'),
('Juliana Costa', 'Outro', 33, 'Diabetes', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Fernanda Silva', 'Masculino', 45, 'Depressão', 'Psicoterapia', 'Dr. Souza', 'Hospital Vida', 'SulAmérica'),
('Ana Souza', 'Feminino', 61, 'Depressão', 'Insulina', 'Dr. Souza', 'Clínica São João', 'Particular'),
('Fernanda Silva', 'Outro', 36, 'Diabetes', 'Psicoterapia', 'Dra. Costa', 'Hospital Vida', 'Particular'),
('Juliana Costa', 'Outro', 67, 'Asma', 'Inalador', 'Dr. Souza', 'Santa Casa', 'Amil'),
('João Pedro', 'Feminino', 73, 'Depressão', 'Beta-bloqueador', 'Dra. Costa', 'Hospital Central', 'Unimed'),
('Lucas Rocha', 'Feminino', 63, 'Obesidade', 'Dieta', 'Dra. Oliveira', 'Clínica São João', 'Unimed'),
('Mariana Alves', 'Masculino', 78, 'Hipertensão', 'Insulina', 'Dra. Oliveira', 'Hospital Central', 'Amil'),
('Juliana Costa', 'Feminino', 23, 'Hipertensão', 'Inalador', 'Dra. Oliveira', 'Clínica São João', 'Amil'),
('Juliana Costa', 'Masculino', 86, 'Diabetes', 'Psicoterapia', 'Dr. Souza', 'Hospital Vida', 'SulAmérica'),
('Fernanda Silva', 'Masculino', 39, 'Obesidade', 'Beta-bloqueador', 'Dra. Oliveira', 'Hospital Vida', 'Unimed'),
('João Pedro', 'Masculino', 86, 'Diabetes', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Particular'),
('João Pedro', 'Masculino', 48, 'Hipertensão', 'Inalador', 'Dr. Souza', 'Santa Casa', 'Amil'),
('Fernanda Silva', 'Feminino', 80, 'Diabetes', 'Beta-bloqueador', 'Dra. Oliveira', 'Clínica São João', 'Bradesco Saúde'),
('Juliana Costa', 'Feminino', 78, 'Covid-19', 'Insulina', 'Dra. Costa', 'Santa Casa', 'Unimed'),
('Beatriz Mendes', 'Feminino', 43, 'Covid-19', 'Dieta', 'Dr. Souza', 'Hospital Vida', 'Particular'),
('Lucas Rocha', 'Outro', 24, 'Diabetes', 'Psicoterapia', 'Dra. Costa', 'Hospital Central', 'Unimed'),
('Lucas Rocha', 'Feminino', 40, 'Obesidade', 'Beta-bloqueador', 'Dra. Costa', 'Santa Casa', 'SulAmérica'),
('Mariana Alves', 'Masculino', 75, 'Depressão', 'Psicoterapia', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Mariana Alves', 'Outro', 34, 'Obesidade', 'Inalador', 'Dra. Oliveira', 'Hospital Vida', 'Unimed'),
('Mariana Alves', 'Masculino', 66, 'Obesidade', 'Dieta', 'Dr. Souza', 'Clínica São João', 'Unimed'),
('João Pedro', 'Outro', 45, 'Depressão', 'Inalador', 'Dra. Costa', 'Hospital Vida', 'Unimed'),
('Beatriz Mendes', 'Feminino', 65, 'Covid-19', 'Beta-bloqueador', 'Dra. Oliveira', 'Clínica São João', 'Bradesco Saúde'),
('Ana Souza', 'Outro', 35, 'Obesidade', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Bradesco Saúde'),
('Fernanda Silva', 'Feminino', 71, 'Covid-19', 'Dieta', 'Dr. Souza', 'Hospital Vida', 'Unimed'),
('João Pedro', 'Feminino', 81, 'Covid-19', 'Insulina', 'Dra. Oliveira', 'Santa Casa', 'Particular'),
('Lucas Rocha', 'Outro', 64, 'Covid-19', 'Insulina', 'Dra. Oliveira', 'Hospital Vida', 'Unimed'),
('Mariana Alves', 'Masculino', 51, 'Obesidade', 'Inalador', 'Dra. Costa', 'Hospital Vida', 'Amil'),
('Ana Souza', 'Feminino', 18, 'Hipertensão', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'SulAmérica'),
('Mariana Alves', 'Outro', 68, 'Depressão', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'Particular'),
('Ana Souza', 'Outro', 60, 'Covid-19', 'Psicoterapia', 'Dra. Costa', 'Hospital Central', 'Unimed'),
('Ana Souza', 'Feminino', 33, 'Depressão', 'Inalador', 'Dra. Costa', 'Clínica São João', 'SulAmérica'),
('Lucas Rocha', 'Outro', 69, 'Depressão', 'Psicoterapia', 'Dra. Costa', 'Clínica São João', 'Amil'),
('Ana Souza', 'Outro', 43, 'Asma', 'Antiviral', 'Dr. Silva', 'Hospital Vida', 'Unimed'),
('Paulo César', 'Outro', 49, 'Covid-19', 'Inalador', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('Beatriz Mendes', 'Outro', 51, 'Depressão', 'Insulina', 'Dr. Souza', 'Santa Casa', 'Particular'),
('Gustavo Dias', 'Feminino', 77, 'Asma', 'Dieta', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Beatriz Mendes', 'Masculino', 35, 'Obesidade', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'SulAmérica'),
('Lucas Rocha', 'Outro', 32, 'Hipertensão', 'Beta-bloqueador', 'Dra. Oliveira', 'Hospital Central', 'Bradesco Saúde'),
('Gustavo Dias', 'Feminino', 70, 'Hipertensão', 'Beta-bloqueador', 'Dr. Souza', 'Hospital Vida', 'Amil'),
('Lucas Rocha', 'Outro', 35, 'Diabetes', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Particular'),
('Gustavo Dias', 'Outro', 29, 'Obesidade', 'Beta-bloqueador', 'Dr. Souza', 'Clínica São João', 'Particular'),
('Paulo César', 'Feminino', 18, 'Asma', 'Inalador', 'Dr. Silva', 'Hospital Central', 'Unimed'),
('Paulo César', 'Feminino', 56, 'Asma', 'Dieta', 'Dr. Silva', 'Hospital Central', 'Particular'),
('Beatriz Mendes', 'Outro', 27, 'Asma', 'Inalador', 'Dr. Souza', 'Clínica São João', 'Unimed'),
('João Pedro', 'Masculino', 54, 'Asma', 'Psicoterapia', 'Dr. Silva', 'Hospital Central', 'SulAmérica'),
('Ana Souza', 'Feminino', 63, 'Covid-19', 'Psicoterapia', 'Dra. Oliveira', 'Clínica São João', 'Bradesco Saúde'),
('Gustavo Dias', 'Outro', 43, 'Depressão', 'Dieta', 'Dra. Costa', 'Clínica São João', 'Particular'),
('Carlos Lima', 'Outro', 24, 'Obesidade', 'Dieta', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('Fernanda Silva', 'Masculino', 18, 'Diabetes', 'Dieta', 'Dr. Souza', 'Hospital Vida', 'Amil'),
('João Pedro', 'Feminino', 62, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Clínica São João', 'Unimed'),
('Beatriz Mendes', 'Masculino', 19, 'Obesidade', 'Dieta', 'Dr. Souza', 'Santa Casa', 'Particular'),
('João Pedro', 'Outro', 73, 'Diabetes', 'Beta-bloqueador', 'Dr. Silva', 'Hospital Central', 'SulAmérica'),
('Mariana Alves', 'Outro', 18, 'Covid-19', 'Dieta', 'Dra. Costa', 'Santa Casa', 'Bradesco Saúde'),
('Ana Souza', 'Masculino', 73, 'Hipertensão', 'Inalador', 'Dra. Oliveira', 'Hospital Central', 'Amil'),
('Juliana Costa', 'Feminino', 76, 'Diabetes', 'Beta-bloqueador', 'Dra. Oliveira', 'Santa Casa', 'Bradesco Saúde'),
('Fernanda Silva', 'Outro', 21, 'Covid-19', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'SulAmérica'),
('Gustavo Dias', 'Masculino', 73, 'Hipertensão', 'Beta-bloqueador', 'Dr. Souza', 'Santa Casa', 'Particular'),
('Mariana Alves', 'Outro', 44, 'Depressão', 'Beta-bloqueador', 'Dr. Souza', 'Santa Casa', 'SulAmérica'),
('Mariana Alves', 'Feminino', 63, 'Asma', 'Dieta', 'Dr. Souza', 'Hospital Vida', 'Amil'),
('Lucas Rocha', 'Feminino', 90, 'Depressão', 'Dieta', 'Dr. Silva', 'Santa Casa', 'SulAmérica'),
('Ana Souza', 'Feminino', 75, 'Covid-19', 'Inalador', 'Dr. Silva', 'Hospital Central', 'Unimed'),
('Beatriz Mendes', 'Masculino', 54, 'Diabetes', 'Beta-bloqueador', 'Dra. Costa', 'Santa Casa', 'SulAmérica'),
('Paulo César', 'Masculino', 49, 'Depressão', 'Dieta', 'Dra. Costa', 'Hospital Vida', 'Unimed'),
('Paulo César', 'Masculino', 85, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Hospital Vida', 'Unimed'),
('Carlos Lima', 'Outro', 77, 'Depressão', 'Insulina', 'Dra. Oliveira', 'Hospital Vida', 'SulAmérica'),
('Beatriz Mendes', 'Outro', 68, 'Diabetes', 'Dieta', 'Dra. Costa', 'Hospital Central', 'Particular'),
('Paulo César', 'Outro', 67, 'Asma', 'Insulina', 'Dra. Oliveira', 'Hospital Central', 'Amil'),
('Mariana Alves', 'Masculino', 34, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Hospital Vida', 'Bradesco Saúde'),
('Beatriz Mendes', 'Outro', 90, 'Covid-19', 'Inalador', 'Dr. Souza', 'Clínica São João', 'Bradesco Saúde'),
('Gustavo Dias', 'Masculino', 71, 'Hipertensão', 'Inalador', 'Dra. Oliveira', 'Hospital Central', 'Unimed'),
('Beatriz Mendes', 'Feminino', 42, 'Hipertensão', 'Dieta', 'Dra. Oliveira', 'Clínica São João', 'SulAmérica'),
('Fernanda Silva', 'Feminino', 85, 'Diabetes', 'Beta-bloqueador', 'Dra. Costa', 'Clínica São João', 'SulAmérica'),
('Beatriz Mendes', 'Outro', 77, 'Obesidade', 'Beta-bloqueador', 'Dra. Costa', 'Clínica São João', 'Amil'),
('Lucas Rocha', 'Masculino', 22, 'Hipertensão', 'Insulina', 'Dr. Silva', 'Clínica São João', 'Particular'),
('Beatriz Mendes', 'Feminino', 55, 'Covid-19', 'Dieta', 'Dr. Silva', 'Hospital Vida', 'SulAmérica'),
('Mariana Alves', 'Feminino', 82, 'Obesidade', 'Inalador', 'Dr. Souza', 'Clínica São João', 'Unimed'),
('Fernanda Silva', 'Masculino', 85, 'Covid-19', 'Psicoterapia', 'Dra. Oliveira', 'Santa Casa', 'Unimed'),
('Juliana Costa', 'Feminino', 41, 'Covid-19', 'Dieta', 'Dra. Oliveira', 'Hospital Central', 'Particular'),
('Fernanda Silva', 'Outro', 46, 'Depressão', 'Dieta', 'Dr. Souza', 'Clínica São João', 'Unimed'),
('Mariana Alves', 'Outro', 36, 'Depressão', 'Inalador', 'Dr. Silva', 'Clínica São João', 'Particular'),
('Mariana Alves', 'Feminino', 61, 'Diabetes', 'Insulina', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('Juliana Costa', 'Feminino', 52, 'Obesidade', 'Antiviral', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Carlos Lima', 'Masculino', 25, 'Obesidade', 'Psicoterapia', 'Dr. Silva', 'Santa Casa', 'Amil'),
('Fernanda Silva', 'Feminino', 68, 'Obesidade', 'Inalador', 'Dr. Souza', 'Hospital Central', 'Particular'),
('Paulo César', 'Masculino', 79, 'Hipertensão', 'Insulina', 'Dr. Souza', 'Hospital Central', 'Unimed'),
('Gustavo Dias', 'Feminino', 85, 'Diabetes', 'Insulina', 'Dra. Oliveira', 'Hospital Central', 'Particular'),
('Mariana Alves', 'Feminino', 55, 'Obesidade', 'Inalador', 'Dr. Silva', 'Santa Casa', 'Amil'),
('Juliana Costa', 'Feminino', 45, 'Asma', 'Insulina', 'Dra. Costa', 'Santa Casa', 'Particular'),
('João Pedro', 'Outro', 67, 'Diabetes', 'Psicoterapia', 'Dra. Costa', 'Hospital Central', 'Amil'),
('Gustavo Dias', 'Masculino', 66, 'Depressão', 'Inalador', 'Dr. Souza', 'Hospital Vida', 'Unimed'),
('Gustavo Dias', 'Outro', 57, 'Asma', 'Psicoterapia', 'Dra. Costa', 'Santa Casa', 'Particular'),
('Carlos Lima', 'Masculino', 59, 'Depressão', 'Antiviral', 'Dra. Oliveira', 'Santa Casa', 'SulAmérica'),
('Ana Souza', 'Masculino', 22, 'Covid-19', 'Beta-bloqueador', 'Dr. Souza', 'Hospital Central', 'Particular'),
('Beatriz Mendes', 'Masculino', 46, 'Obesidade', 'Antiviral', 'Dra. Oliveira', 'Hospital Vida', 'Amil'),
('Lucas Rocha', 'Masculino', 85, 'Asma', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'Unimed'),
('Lucas Rocha', 'Masculino', 27, 'Diabetes', 'Psicoterapia', 'Dr. Silva', 'Clínica São João', 'Particular'),
('Carlos Lima', 'Outro', 73, 'Depressão', 'Psicoterapia', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('João Pedro', 'Masculino', 87, 'Hipertensão', 'Dieta', 'Dra. Oliveira', 'Hospital Central', 'SulAmérica'),
('Juliana Costa', 'Masculino', 70, 'Asma', 'Antiviral', 'Dra. Costa', 'Clínica São João', 'Bradesco Saúde'),
('Mariana Alves', 'Masculino', 31, 'Depressão', 'Insulina', 'Dra. Oliveira', 'Clínica São João', 'Particular'),
('Fernanda Silva', 'Outro', 79, 'Obesidade', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Bradesco Saúde'),
('João Pedro', 'Feminino', 29, 'Asma', 'Psicoterapia', 'Dra. Oliveira', 'Hospital Vida', 'Amil'),
('Gustavo Dias', 'Masculino', 77, 'Hipertensão', 'Dieta', 'Dra. Oliveira', 'Hospital Vida', 'Unimed'),
('Juliana Costa', 'Outro', 57, 'Diabetes', 'Dieta', 'Dr. Souza', 'Clínica São João', 'Unimed'),
('Ana Souza', 'Outro', 78, 'Depressão', 'Antiviral', 'Dra. Oliveira', 'Hospital Vida', 'Amil'),
('Lucas Rocha', 'Masculino', 40, 'Covid-19', 'Dieta', 'Dra. Oliveira', 'Hospital Central', 'Amil'),
('Juliana Costa', 'Feminino', 61, 'Depressão', 'Dieta', 'Dr. Silva', 'Hospital Central', 'Amil'),
('Lucas Rocha', 'Masculino', 57, 'Obesidade', 'Beta-bloqueador', 'Dr. Souza', 'Santa Casa', 'Unimed'),
('Fernanda Silva', 'Masculino', 67, 'Asma', 'Dieta', 'Dra. Oliveira', 'Hospital Central', 'Particular'),
('Gustavo Dias', 'Feminino', 61, 'Depressão', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Gustavo Dias', 'Masculino', 77, 'Diabetes', 'Psicoterapia', 'Dra. Oliveira', 'Hospital Central', 'Particular'),
('Gustavo Dias', 'Masculino', 81, 'Obesidade', 'Psicoterapia', 'Dr. Souza', 'Santa Casa', 'Bradesco Saúde'),
('Fernanda Silva', 'Outro', 39, 'Hipertensão', 'Inalador', 'Dr. Silva', 'Hospital Vida', 'SulAmérica'),
('Mariana Alves', 'Feminino', 54, 'Obesidade', 'Dieta', 'Dra. Costa', 'Hospital Vida', 'Bradesco Saúde'),
('Juliana Costa', 'Feminino', 28, 'Diabetes', 'Dieta', 'Dr. Souza', 'Clínica São João', 'SulAmérica'),
('João Pedro', 'Feminino', 33, 'Obesidade', 'Psicoterapia', 'Dra. Oliveira', 'Hospital Central', 'SulAmérica'),
('Juliana Costa', 'Feminino', 34, 'Diabetes', 'Inalador', 'Dr. Silva', 'Santa Casa', 'Bradesco Saúde'),
('Ana Souza', 'Feminino', 51, 'Covid-19', 'Psicoterapia', 'Dra. Costa', 'Clínica São João', 'Bradesco Saúde'),
('Beatriz Mendes', 'Masculino', 55, 'Hipertensão', 'Beta-bloqueador', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Juliana Costa', 'Masculino', 74, 'Obesidade', 'Inalador', 'Dra. Costa', 'Clínica São João', 'SulAmérica'),
('Juliana Costa', 'Masculino', 89, 'Diabetes', 'Antiviral', 'Dra. Oliveira', 'Clínica São João', 'Particular'),
('Gustavo Dias', 'Masculino', 79, 'Hipertensão', 'Inalador', 'Dr. Souza', 'Hospital Central', 'Amil'),
('Fernanda Silva', 'Feminino', 57, 'Diabetes', 'Dieta', 'Dra. Costa', 'Clínica São João', 'Particular'),
('Lucas Rocha', 'Masculino', 49, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Particular'),
('Paulo César', 'Feminino', 24, 'Obesidade', 'Insulina', 'Dra. Costa', 'Santa Casa', 'Particular'),
('Fernanda Silva', 'Outro', 61, 'Diabetes', 'Inalador', 'Dra. Oliveira', 'Clínica São João', 'SulAmérica'),
('Fernanda Silva', 'Feminino', 39, 'Depressão', 'Antiviral', 'Dra. Oliveira', 'Clínica São João', 'SulAmérica'),
('Mariana Alves', 'Outro', 80, 'Obesidade', 'Inalador', 'Dra. Costa', 'Clínica São João', 'Amil'),
('Mariana Alves', 'Feminino', 72, 'Depressão', 'Psicoterapia', 'Dra. Costa', 'Santa Casa', 'SulAmérica'),
('Mariana Alves', 'Masculino', 84, 'Obesidade', 'Antiviral', 'Dr. Silva', 'Hospital Vida', 'SulAmérica'),
('Carlos Lima', 'Masculino', 77, 'Diabetes', 'Dieta', 'Dra. Oliveira', 'Hospital Vida', 'Amil'),
('Mariana Alves', 'Feminino', 81, 'Depressão', 'Dieta', 'Dra. Costa', 'Clínica São João', 'Bradesco Saúde'),
('Beatriz Mendes', 'Masculino', 37, 'Hipertensão', 'Insulina', 'Dr. Silva', 'Hospital Vida', 'Bradesco Saúde'),
('João Pedro', 'Masculino', 22, 'Obesidade', 'Beta-bloqueador', 'Dra. Oliveira', 'Santa Casa', 'Bradesco Saúde'),
('Paulo César', 'Outro', 20, 'Hipertensão', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Paulo César', 'Outro', 78, 'Hipertensão', 'Insulina', 'Dra. Costa', 'Hospital Central', 'SulAmérica'),
('Gustavo Dias', 'Feminino', 70, 'Depressão', 'Insulina', 'Dr. Souza', 'Hospital Vida', 'Unimed'),
('Beatriz Mendes', 'Masculino', 38, 'Diabetes', 'Antiviral', 'Dra. Oliveira', 'Hospital Vida', 'Particular'),
('João Pedro', 'Masculino', 64, 'Obesidade', 'Antiviral', 'Dra. Oliveira', 'Hospital Vida', 'Particular'),
('Mariana Alves', 'Feminino', 90, 'Depressão', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Bradesco Saúde'),
('Ana Souza', 'Outro', 69, 'Diabetes', 'Insulina', 'Dra. Costa', 'Hospital Vida', 'Bradesco Saúde'),
('Paulo César', 'Outro', 60, 'Covid-19', 'Dieta', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Ana Souza', 'Masculino', 24, 'Hipertensão', 'Inalador', 'Dra. Costa', 'Hospital Central', 'Particular'),
('Beatriz Mendes', 'Outro', 22, 'Depressão', 'Antiviral', 'Dra. Costa', 'Clínica São João', 'Particular'),
('João Pedro', 'Feminino', 60, 'Diabetes', 'Dieta', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Lucas Rocha', 'Masculino', 84, 'Depressão', 'Insulina', 'Dr. Silva', 'Santa Casa', 'Amil'),
('João Pedro', 'Outro', 48, 'Diabetes', 'Inalador', 'Dr. Silva', 'Santa Casa', 'Unimed'),
('Fernanda Silva', 'Feminino', 60, 'Covid-19', 'Inalador', 'Dr. Silva', 'Hospital Central', 'Bradesco Saúde'),
('Ana Souza', 'Feminino', 22, 'Covid-19', 'Insulina', 'Dr. Silva', 'Hospital Central', 'Particular'),
('Mariana Alves', 'Masculino', 88, 'Diabetes', 'Insulina', 'Dra. Costa', 'Hospital Central', 'SulAmérica'),
('Fernanda Silva', 'Feminino', 24, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Particular'),
('Beatriz Mendes', 'Feminino', 39, 'Hipertensão', 'Insulina', 'Dr. Silva', 'Hospital Central', 'Unimed'),
('Paulo César', 'Feminino', 73, 'Diabetes', 'Beta-bloqueador', 'Dra. Costa', 'Clínica São João', 'Bradesco Saúde'),
('Carlos Lima', 'Outro', 70, 'Covid-19', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'SulAmérica'),
('Gustavo Dias', 'Feminino', 57, 'Obesidade', 'Inalador', 'Dr. Souza', 'Clínica São João', 'Amil'),
('Gustavo Dias', 'Outro', 31, 'Asma', 'Beta-bloqueador', 'Dra. Oliveira', 'Clínica São João', 'Particular'),
('Paulo César', 'Outro', 41, 'Hipertensão', 'Dieta', 'Dra. Costa', 'Clínica São João', 'Bradesco Saúde'),
('Paulo César', 'Feminino', 46, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Clínica São João', 'Amil'),
('Mariana Alves', 'Outro', 32, 'Obesidade', 'Inalador', 'Dr. Silva', 'Santa Casa', 'SulAmérica'),
('Lucas Rocha', 'Feminino', 22, 'Asma', 'Dieta', 'Dr. Souza', 'Santa Casa', 'Amil'),
('Lucas Rocha', 'Outro', 76, 'Diabetes', 'Insulina', 'Dr. Souza', 'Hospital Vida', 'Amil'),
('Ana Souza', 'Masculino', 69, 'Diabetes', 'Psicoterapia', 'Dr. Silva', 'Clínica São João', 'Bradesco Saúde'),
('João Pedro', 'Outro', 58, 'Obesidade', 'Dieta', 'Dra. Costa', 'Santa Casa', 'Bradesco Saúde'),
('Ana Souza', 'Outro', 76, 'Diabetes', 'Beta-bloqueador', 'Dr. Souza', 'Santa Casa', 'SulAmérica'),
('Fernanda Silva', 'Outro', 53, 'Covid-19', 'Psicoterapia', 'Dr. Silva', 'Santa Casa', 'Amil'),
('Gustavo Dias', 'Outro', 31, 'Depressão', 'Beta-bloqueador', 'Dra. Oliveira', 'Hospital Central', 'Amil'),
('João Pedro', 'Feminino', 79, 'Diabetes', 'Antiviral', 'Dr. Silva', 'Santa Casa', 'Particular'),
('Ana Souza', 'Outro', 47, 'Obesidade', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Bradesco Saúde'),
('Juliana Costa', 'Masculino', 39, 'Diabetes', 'Psicoterapia', 'Dra. Costa', 'Hospital Central', 'Amil'),
('Carlos Lima', 'Outro', 41, 'Hipertensão', 'Psicoterapia', 'Dr. Souza', 'Hospital Vida', 'Particular'),
('Gustavo Dias', 'Outro', 36, 'Asma', 'Psicoterapia', 'Dr. Souza', 'Santa Casa', 'Bradesco Saúde'),
('Beatriz Mendes', 'Outro', 25, 'Diabetes', 'Psicoterapia', 'Dra. Costa', 'Hospital Central', 'Unimed'),
('Ana Souza', 'Feminino', 36, 'Covid-19', 'Antiviral', 'Dr. Silva', 'Santa Casa', 'Bradesco Saúde'),
('Ana Souza', 'Outro', 28, 'Obesidade', 'Beta-bloqueador', 'Dr. Souza', 'Hospital Central', 'Amil'),
('Beatriz Mendes', 'Masculino', 63, 'Obesidade', 'Psicoterapia', 'Dra. Costa', 'Hospital Central', 'Particular'),
('Juliana Costa', 'Outro', 58, 'Hipertensão', 'Dieta', 'Dra. Oliveira', 'Santa Casa', 'Particular'),
('Ana Souza', 'Feminino', 57, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Clínica São João', 'Particular'),
('Mariana Alves', 'Outro', 69, 'Asma', 'Inalador', 'Dr. Silva', 'Hospital Central', 'SulAmérica'),
('Mariana Alves', 'Masculino', 70, 'Diabetes', 'Dieta', 'Dr. Souza', 'Hospital Central', 'Amil'),
('Ana Souza', 'Masculino', 19, 'Asma', 'Inalador', 'Dra. Costa', 'Hospital Central', 'Particular'),
('Beatriz Mendes', 'Masculino', 85, 'Covid-19', 'Insulina', 'Dr. Souza', 'Clínica São João', 'Particular'),
('Paulo César', 'Outro', 21, 'Depressão', 'Insulina', 'Dra. Oliveira', 'Hospital Vida', 'Unimed'),
('Juliana Costa', 'Masculino', 86, 'Diabetes', 'Inalador', 'Dra. Costa', 'Santa Casa', 'Unimed'),
('Beatriz Mendes', 'Outro', 63, 'Diabetes', 'Beta-bloqueador', 'Dra. Costa', 'Clínica São João', 'Bradesco Saúde'),
('Ana Souza', 'Masculino', 23, 'Diabetes', 'Beta-bloqueador', 'Dr. Silva', 'Clínica São João', 'SulAmérica'),
('Paulo César', 'Outro', 28, 'Hipertensão', 'Dieta', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Lucas Rocha', 'Masculino', 79, 'Covid-19', 'Antiviral', 'Dr. Souza', 'Clínica São João', 'Amil'),
('Beatriz Mendes', 'Outro', 57, 'Covid-19', 'Psicoterapia', 'Dra. Oliveira', 'Hospital Vida', 'Bradesco Saúde'),
('Fernanda Silva', 'Feminino', 36, 'Asma', 'Insulina', 'Dr. Silva', 'Clínica São João', 'Amil'),
('Carlos Lima', 'Outro', 65, 'Depressão', 'Dieta', 'Dra. Oliveira', 'Hospital Central', 'Bradesco Saúde'),
('Paulo César', 'Outro', 65, 'Asma', 'Inalador', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('Gustavo Dias', 'Outro', 63, 'Asma', 'Antiviral', 'Dr. Silva', 'Santa Casa', 'SulAmérica'),
('Fernanda Silva', 'Masculino', 77, 'Diabetes', 'Insulina', 'Dra. Costa', 'Hospital Central', 'Particular'),
('Ana Souza', 'Outro', 37, 'Diabetes', 'Insulina', 'Dr. Silva', 'Santa Casa', 'SulAmérica'),
('Ana Souza', 'Outro', 47, 'Asma', 'Dieta', 'Dra. Costa', 'Clínica São João', 'SulAmérica'),
('Ana Souza', 'Feminino', 30, 'Diabetes', 'Psicoterapia', 'Dra. Oliveira', 'Santa Casa', 'Bradesco Saúde'),
('Lucas Rocha', 'Feminino', 39, 'Hipertensão', 'Antiviral', 'Dr. Souza', 'Hospital Central', 'Unimed'),
('Fernanda Silva', 'Masculino', 34, 'Hipertensão', 'Beta-bloqueador', 'Dr. Silva', 'Santa Casa', 'Particular'),
('Carlos Lima', 'Masculino', 18, 'Asma', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Particular'),
('Fernanda Silva', 'Feminino', 35, 'Asma', 'Inalador', 'Dra. Costa', 'Santa Casa', 'Bradesco Saúde'),
('Fernanda Silva', 'Masculino', 71, 'Depressão', 'Dieta', 'Dra. Oliveira', 'Santa Casa', 'Unimed'),
('Paulo César', 'Feminino', 64, 'Diabetes', 'Insulina', 'Dr. Silva', 'Hospital Central', 'Bradesco Saúde'),
('Beatriz Mendes', 'Feminino', 63, 'Obesidade', 'Inalador', 'Dra. Costa', 'Clínica São João', 'Amil'),
('Juliana Costa', 'Masculino', 43, 'Asma', 'Beta-bloqueador', 'Dr. Souza', 'Santa Casa', 'Bradesco Saúde'),
('Paulo César', 'Masculino', 39, 'Hipertensão', 'Inalador', 'Dr. Souza', 'Clínica São João', 'Particular'),
('Paulo César', 'Feminino', 53, 'Obesidade', 'Beta-bloqueador', 'Dr. Silva', 'Santa Casa', 'SulAmérica'),
('Carlos Lima', 'Masculino', 39, 'Hipertensão', 'Insulina', 'Dr. Souza', 'Hospital Vida', 'SulAmérica'),
('Fernanda Silva', 'Masculino', 37, 'Covid-19', 'Psicoterapia', 'Dr. Silva', 'Santa Casa', 'Particular'),
('Carlos Lima', 'Masculino', 66, 'Obesidade', 'Inalador', 'Dra. Costa', 'Hospital Central', 'Amil'),
('Beatriz Mendes', 'Feminino', 64, 'Covid-19', 'Dieta', 'Dra. Oliveira', 'Santa Casa', 'Bradesco Saúde'),
('Lucas Rocha', 'Feminino', 61, 'Obesidade', 'Antiviral', 'Dr. Silva', 'Santa Casa', 'Amil'),
('Beatriz Mendes', 'Masculino', 80, 'Obesidade', 'Beta-bloqueador', 'Dra. Oliveira', 'Santa Casa', 'Amil'),
('João Pedro', 'Outro', 76, 'Diabetes', 'Psicoterapia', 'Dra. Costa', 'Hospital Vida', 'Amil'),
('Paulo César', 'Masculino', 70, 'Obesidade', 'Psicoterapia', 'Dra. Oliveira', 'Santa Casa', 'Bradesco Saúde'),
('Carlos Lima', 'Feminino', 28, 'Diabetes', 'Inalador', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('Carlos Lima', 'Feminino', 50, 'Covid-19', 'Beta-bloqueador', 'Dr. Souza', 'Hospital Central', 'Unimed'),
('Juliana Costa', 'Feminino', 39, 'Diabetes', 'Psicoterapia', 'Dr. Silva', 'Clínica São João', 'Amil'),
('Fernanda Silva', 'Masculino', 74, 'Covid-19', 'Antiviral', 'Dr. Silva', 'Clínica São João', 'Bradesco Saúde'),
('Mariana Alves', 'Feminino', 84, 'Depressão', 'Psicoterapia', 'Dr. Silva', 'Hospital Vida', 'Bradesco Saúde'),
('Mariana Alves', 'Masculino', 28, 'Depressão', 'Dieta', 'Dra. Costa', 'Clínica São João', 'Unimed'),
('João Pedro', 'Outro', 70, 'Hipertensão', 'Insulina', 'Dra. Oliveira', 'Hospital Central', 'Bradesco Saúde'),
('Fernanda Silva', 'Masculino', 62, 'Covid-19', 'Insulina', 'Dr. Souza', 'Santa Casa', 'Amil'),
('Paulo César', 'Masculino', 63, 'Diabetes', 'Dieta', 'Dra. Oliveira', 'Hospital Vida', 'Amil'),
('Fernanda Silva', 'Masculino', 89, 'Covid-19', 'Inalador', 'Dr. Silva', 'Hospital Vida', 'Unimed'),
('Ana Souza', 'Feminino', 40, 'Covid-19', 'Beta-bloqueador', 'Dra. Costa', 'Hospital Vida', 'Bradesco Saúde'),
('Ana Souza', 'Outro', 88, 'Obesidade', 'Beta-bloqueador', 'Dr. Souza', 'Santa Casa', 'Particular'),
('Ana Souza', 'Masculino', 50, 'Obesidade', 'Psicoterapia', 'Dra. Costa', 'Hospital Vida', 'Bradesco Saúde'),
('Gustavo Dias', 'Outro', 74, 'Depressão', 'Dieta', 'Dra. Costa', 'Hospital Vida', 'SulAmérica'),
('Fernanda Silva', 'Masculino', 62, 'Asma', 'Dieta', 'Dra. Costa', 'Santa Casa', 'Particular'),
('Carlos Lima', 'Feminino', 52, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Gustavo Dias', 'Masculino', 69, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Hospital Central', 'Amil'),
('Gustavo Dias', 'Outro', 33, 'Obesidade', 'Dieta', 'Dr. Souza', 'Santa Casa', 'Particular'),
('Paulo César', 'Masculino', 44, 'Hipertensão', 'Inalador', 'Dr. Silva', 'Hospital Central', 'Amil'),
('Beatriz Mendes', 'Masculino', 46, 'Asma', 'Dieta', 'Dra. Oliveira', 'Clínica São João', 'Amil'),
('Juliana Costa', 'Feminino', 57, 'Covid-19', 'Inalador', 'Dra. Oliveira', 'Santa Casa', 'Particular'),
('Carlos Lima', 'Feminino', 88, 'Depressão', 'Dieta', 'Dra. Oliveira', 'Clínica São João', 'SulAmérica'),
('Lucas Rocha', 'Masculino', 52, 'Asma', 'Inalador', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Paulo César', 'Feminino', 69, 'Obesidade', 'Dieta', 'Dr. Souza', 'Clínica São João', 'Bradesco Saúde'),
('Mariana Alves', 'Feminino', 80, 'Asma', 'Antiviral', 'Dra. Oliveira', 'Clínica São João', 'Unimed'),
('Gustavo Dias', 'Outro', 53, 'Diabetes', 'Beta-bloqueador', 'Dra. Oliveira', 'Santa Casa', 'Particular'),
('Mariana Alves', 'Outro', 53, 'Asma', 'Beta-bloqueador', 'Dra. Costa', 'Clínica São João', 'Unimed'),
('Lucas Rocha', 'Feminino', 40, 'Hipertensão', 'Beta-bloqueador', 'Dr. Silva', 'Hospital Central', 'Unimed'),
('Fernanda Silva', 'Masculino', 79, 'Hipertensão', 'Antiviral', 'Dra. Oliveira', 'Hospital Vida', 'Unimed'),
('Lucas Rocha', 'Outro', 27, 'Diabetes', 'Beta-bloqueador', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Paulo César', 'Masculino', 81, 'Obesidade', 'Beta-bloqueador', 'Dr. Silva', 'Santa Casa', 'Amil'),
('Ana Souza', 'Outro', 44, 'Covid-19', 'Beta-bloqueador', 'Dra. Costa', 'Clínica São João', 'Unimed'),
('Beatriz Mendes', 'Feminino', 38, 'Asma', 'Beta-bloqueador', 'Dra. Oliveira', 'Hospital Vida', 'Particular'),
('Ana Souza', 'Masculino', 83, 'Asma', 'Antiviral', 'Dr. Souza', 'Clínica São João', 'SulAmérica'),
('Mariana Alves', 'Outro', 57, 'Obesidade', 'Insulina', 'Dr. Silva', 'Hospital Vida', 'Amil'),
('Beatriz Mendes', 'Feminino', 19, 'Asma', 'Antiviral', 'Dr. Souza', 'Santa Casa', 'Amil'),
('Juliana Costa', 'Outro', 68, 'Depressão', 'Inalador', 'Dr. Silva', 'Clínica São João', 'Amil'),
('Ana Souza', 'Feminino', 23, 'Covid-19', 'Insulina', 'Dra. Oliveira', 'Hospital Central', 'SulAmérica'),
('Lucas Rocha', 'Masculino', 82, 'Hipertensão', 'Psicoterapia', 'Dr. Silva', 'Clínica São João', 'Particular'),
('João Pedro', 'Outro', 39, 'Depressão', 'Insulina', 'Dra. Costa', 'Hospital Vida', 'Particular'),
('Fernanda Silva', 'Feminino', 84, 'Covid-19', 'Beta-bloqueador', 'Dr. Silva', 'Santa Casa', 'Unimed'),
('João Pedro', 'Feminino', 53, 'Asma', 'Antiviral', 'Dra. Costa', 'Hospital Vida', 'Particular'),
('Lucas Rocha', 'Masculino', 81, 'Diabetes', 'Beta-bloqueador', 'Dra. Oliveira', 'Hospital Vida', 'Bradesco Saúde'),
('Carlos Lima', 'Masculino', 22, 'Obesidade', 'Insulina', 'Dr. Silva', 'Santa Casa', 'Unimed'),
('Carlos Lima', 'Masculino', 75, 'Obesidade', 'Antiviral', 'Dr. Souza', 'Clínica São João', 'Bradesco Saúde'),
('Paulo César', 'Masculino', 46, 'Asma', 'Antiviral', 'Dr. Souza', 'Santa Casa', 'SulAmérica'),
('Lucas Rocha', 'Masculino', 75, 'Depressão', 'Inalador', 'Dra. Costa', 'Hospital Central', 'Bradesco Saúde'),
('Paulo César', 'Outro', 23, 'Asma', 'Beta-bloqueador', 'Dr. Silva', 'Hospital Vida', 'Bradesco Saúde'),
('Gustavo Dias', 'Feminino', 70, 'Depressão', 'Psicoterapia', 'Dr. Silva', 'Hospital Central', 'Bradesco Saúde'),
('Mariana Alves', 'Feminino', 79, 'Obesidade', 'Insulina', 'Dr. Silva', 'Clínica São João', 'SulAmérica'),
('João Pedro', 'Masculino', 86, 'Depressão', 'Antiviral', 'Dr. Silva', 'Hospital Vida', 'SulAmérica'),
('Paulo César', 'Feminino', 73, 'Obesidade', 'Inalador', 'Dra. Costa', 'Hospital Central', 'Bradesco Saúde'),
('Fernanda Silva', 'Masculino', 54, 'Depressão', 'Antiviral', 'Dra. Costa', 'Santa Casa', 'Amil'),
('Carlos Lima', 'Masculino', 51, 'Diabetes', 'Psicoterapia', 'Dr. Souza', 'Hospital Central', 'Amil'),
('Fernanda Silva', 'Feminino', 43, 'Diabetes', 'Antiviral', 'Dra. Costa', 'Hospital Vida', 'Particular'),
('Mariana Alves', 'Masculino', 83, 'Depressão', 'Beta-bloqueador', 'Dra. Costa', 'Hospital Central', 'SulAmérica'),
('Beatriz Mendes', 'Outro', 53, 'Obesidade', 'Antiviral', 'Dr. Souza', 'Hospital Central', 'Bradesco Saúde'),
('Juliana Costa', 'Masculino', 74, 'Depressão', 'Psicoterapia', 'Dr. Souza', 'Hospital Vida', 'Unimed'),
('Fernanda Silva', 'Outro', 66, 'Hipertensão', 'Psicoterapia', 'Dra. Oliveira', 'Santa Casa', 'Particular'),
('Fernanda Silva', 'Feminino', 73, 'Obesidade', 'Psicoterapia', 'Dra. Costa', 'Santa Casa', 'Bradesco Saúde'),
('Fernanda Silva', 'Outro', 23, 'Asma', 'Beta-bloqueador', 'Dra. Oliveira', 'Clínica São João', 'SulAmérica'),
('João Pedro', 'Masculino', 76, 'Covid-19', 'Insulina', 'Dr. Souza', 'Clínica São João', 'Amil'),
('Lucas Rocha', 'Feminino', 41, 'Diabetes', 'Antiviral', 'Dr. Silva', 'Hospital Central', 'Bradesco Saúde'),
('Fernanda Silva', 'Masculino', 82, 'Diabetes', 'Psicoterapia', 'Dra. Oliveira', 'Clínica São João', 'Unimed'),
('Carlos Lima', 'Feminino', 76, 'Obesidade', 'Insulina', 'Dra. Oliveira', 'Santa Casa', 'Amil'),
('Beatriz Mendes', 'Masculino', 26, 'Covid-19', 'Antiviral', 'Dra. Oliveira', 'Hospital Central', 'Bradesco Saúde'),
('Gustavo Dias', 'Feminino', 53, 'Obesidade', 'Dieta', 'Dra. Costa', 'Santa Casa', 'Unimed'),
('Juliana Costa', 'Outro', 22, 'Obesidade', 'Psicoterapia', 'Dra. Costa', 'Clínica São João', 'Particular');
